# action.yml
name: "Addon Factory Sample Scanner"
description: "Detect potentially sensitive data in samples"
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/setup.sh
      shell: bash
    - run: go-earlybird  -show-solutions -suppress -config=/.go-earlybird/  -ignorefile=/.ge_ignore -path=${GITHUB_WORKSPACE}/${INPUT_SCANDIR} ${INPUT_ARGS}
      shell: bash
inputs:
  args:
    description: Additional arguments to the scanner
    required: false
  Path:
    required: false
  ScanDir:
    description: Set the scan directory relative to the project
    required: false
    default: tests/knowledge
