# action.yml
name: "Addon Factory Sample Scanner"
description: "Detect potentially sensitive data in samples"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  args:
    description: Additional arguments to the scanner
    required: false
  Path:
    required: false
    default: $GITHUB_WORKSPACE
  ScanDir:
    description: Set the scan directory relative to the project
    required: false
    default: tests/knowledge
