# action.yml
name: "Addon Factory Sample Scanner"
description: "Detect potentially sensitive data in samples"
runs:
  using: "docker"
  image: "docker://ghcr.io/splunk/addonfactory-sample-scanner:v1.0.7"
inputs:
  args:
    description: Additional arguments to the scanner
    required: false
  Path:
    required: false
  ScanDir:
    description: Set the scan directory relative to the project
    required: false
    default: tests/knowledge
