# action.yml
name: "Addon Factory Sample Scanner"
description: "Detect potentially sensitive data in samples"
inputs:
  path: # id of input
    description: "Path to samples"
    required: true
    default: -path=$(PWD)/tests/knowledge
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
