on: [push]

jobs:
  sample_scanner:
    runs-on: ubuntu-latest
    name: Run sample scanner
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build earlybird
        run: |
          cd earlybird
          ./build.sh
          cd ..
      - name: sample-scanner
        uses: ./ # Uses an action in the root directory
        id: sample-scanner
        with:
          path: "/var/log"
